### ISSUE TITLE
Blender 4.1.0 doesn't work

### ISSUE THREAD

**Issue by BaalNetbek** [vosen/ZLUDA#186] opened 2024-03-28 17:12 UTC
In Blender after update (4.0.3 -> 4.1.0) Optix doesn't render (shows only silhouettes of objects) with CUDA with my RX 570 [Zluda]. It works in previous versions. 
That's what it says trough console right after trying to render with ZLUDA.
```
Failed to configure CUDA context (Invalid context)

Refer to the Cycles GPU rendering documentation for possible solutions:
https://docs.blender.org/manual/en/latest/render/cycles/gpu_rendering.html

Invalid value in cuCtxPushCurrent(device->cuContext) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\util.cpp:14)
Invalid context in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Invalid context in cuCtxPopCurrent(NULL) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\util.cpp:19)
```
The files from log: [https://github.com/blender/blender/tree/main/intern/cycles/device/cuda](https://github.com/blender/blender/tree/main/intern/cycles/device/cuda)
I suppose it was broken on purpose.

**Comment by vosen** [comment] 2024-03-28 17:42
I think that's duplicate of #146. Can you try the newest ZLUDA revision?

**Comment by BaalNetbek** [comment] 2024-03-28 20:40
I just tested now and it's working with latest rev. 
Thank you.

I will leave here compilation of todays state of the repository as took my computer 30 minutes to compile.
[zluda-3-windows_7d4147c.zip](https://github.com/vosen/ZLUDA/files/14795187/zluda-3-windows_7d4147c.zip)

**Closed** 2024-03-28 20:41 UTC
